name: Azure DevOps Migration

on:
  workflow_dispatch:
    inputs:
      source_org:
        description: "Source Azure DevOps Organization Name"
        required: true
        type: string
      source_project:
        description: "Source Project Name"
        required: true
        type: string
      destination_project:
        description: "Destination Project Name"
        required: true
        type: string

jobs:
  run-migration:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Download DevOps Migration Tools ZIP
      run: |
        Invoke-WebRequest `
          -Uri "https://github.com/nkdAgility/azure-devops-migration-tools/releases/download/13.10.30.0/portable.zip" `
          -OutFile "migrationtools.zip"
    - name: Extract DevOps Migration Tools
      run: Expand-Archive -Path "migrationtools.zip" -DestinationPath "migration"

    - name: Generate config.json dynamically
      shell: pwsh
      run: |
        $config = Get-Content ".\configuration.json" | ConvertFrom-Json

        $config.MigrationTools.Endpoints.Source.Collection = "https://dev.azure.com/${{ github.event.inputs.source_org }}/"
        $config.MigrationTools.Endpoints.Source.Project = "${{ github.event.inputs.source_project }}"
        $config.MigrationTools.Endpoints.Source.Authentication.AccessToken = "${{ secrets.SOURCE_PAT }}"

        $config.MigrationTools.Endpoints.Target.Collection = "https://dev.azure.com/balraj-test-org/"
        $config.MigrationTools.Endpoints.Target.Project = "${{ github.event.inputs.destination_project }}"
        $config.MigrationTools.Endpoints.Target.Authentication.AccessToken = "${{ secrets.DESTINATION_PAT }}"

        $config | ConvertTo-Json -Depth 100 | Out-File ".\migration\config.json" -Encoding utf8

    - name: Run Migration
      shell: powershell
      run: .\migration\devopsmigration.exe execute -c config.json
      working-directory: ./migration
