name: DevOps Migration via CLI

on:
  workflow_dispatch:
    inputs:
      source_org:
        description: "Source Azure DevOps Organization Name"
        required: true
        type: string
      source_project:
        description: "Source Project Name"
        required: true
        type: string
      destination_project:
        description: "Destination Project Name"
        required: true
        type: string

jobs:
  run-migration:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install and Repair WinGet on GitHub Runner
      shell: powershell
      run: |
        $progressPreference = 'silentlyContinue'
        Write-Host "Installing WinGet PowerShell module from PSGallery..."
        Install-PackageProvider -Name NuGet -Force | Out-Null
        Install-Module -Name Microsoft.WinGet.Client -Force -Repository PSGallery -AllowClobber | Out-Null
        Write-Host "Using Repair-WinGetPackageManager cmdlet to bootstrap WinGet..."
        Repair-WinGetPackageManager
        Write-Host "Done."

    - name: Install DevOpsMigration CLI using WinGet
      shell: powershell
      run: |
        winget install --id=nakedAgility.DevOpsMigrationTools --accept-source-agreements --accept-package-agreements

    - name: Modify configuration.json from template
      shell: powershell
      run: |
        $config = Get-Content "configuration.json" | ConvertFrom-Json

        # Inject Source Configuration
        $config.MigrationTools.Endpoints.Source.Collection = "https://dev.azure.com/${{ github.event.inputs.source_org }}/"
        $config.MigrationTools.Endpoints.Source.Project = "${{ github.event.inputs.source_project }}"
        $config.MigrationTools.Endpoints.Source.Authentication.AccessToken = "${{ secrets.SOURCE_PAT }}"

        # Inject Target Configuration (destination org is hardcoded)
        $config.MigrationTools.Endpoints.Target.Collection = "https://dev.azure.com/balraj-test-org/"
        $config.MigrationTools.Endpoints.Target.Project = "${{ github.event.inputs.destination_project }}"
        $config.MigrationTools.Endpoints.Target.Authentication.AccessToken = "${{ secrets.DESTINATION_PAT }}"

        # Save modified config
        $config | ConvertTo-Json -Depth 100 | Out-File "config.json" -Encoding utf8

    - name: Run DevOps Migration
      shell: powershell
      run: |
        devopsmigration execute -c config.json
