name: Manual Migration Trigger

on:
  workflow_dispatch:
    inputs:
      source_organization:
        description: 'Name of the source organization'
        required: true
        default: 'Unique-organisation'
        type: string
      source_project:
        description: 'Name of the source project'
        required: true
        default: 'Unique'
        type: string
      destination_project:
        description: 'Name of the destination project'
        required: true
        default: 'Unique'
        type: string
      
jobs:
  run-migration:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install winget
        uses: Cyberboss/install-winget@v1
          
      - name: Download Azure DevOps Migration Tools
        run: |
          Invoke-WebRequest -Uri "https://github.com/nkdAgility/azure-devops-migration-tools/releases/download/v16.1.0/MigrationTools-16.1.0.zip" -OutFile "migration.zip"
          Expand-Archive -Path "migration.zip" -DestinationPath "migration-tools"
        shell: pwsh

      - name: Replace secrets in configuration file
        run: |

          $template = Get-Content configuration.template.json -Raw
          $template = $template -replace '__SOURCE_ORG__', "${{ inputs.source_organization }}"
          $template = $template -replace '__SOURCE_PROJECT__', "${{ inputs.source_project }}"
          $template = $template -replace '__SOURCE_PAT__', "${{ secrets.SOURCE_PAT }}"
          $template = $template -replace '__TARGET_PROJECT__', "${{ inputs.destination_project }}"
          $template = $template -replace '__TARGET_PAT__', "${{ secrets.DESTINATION_PAT }}"
          Set-Content -Path configuration.json -Value $template
        shell: pwsh

      - name: Run Migration Tool
        run: |
          ./migration-tools/devopsmigration.exe execute -c configuration.json
        shell: pwsh
