name: DevOps Migration via CLI

on:
  workflow_dispatch:
    inputs:
      source_org:
        description: "Source Azure DevOps Organization Name"
        required: true
        type: string
      source_project:
        description: "Source Project Name"
        required: true
        type: string
      destination_project:
        description: "Destination Project Name"
        required: true
        type: string

jobs:
  run-migration:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install DevOpsMigration CLI via Chocolatey
      shell: powershell
      run: |
        choco install devopsmigrationtools -y

    - name: Modify configuration.json from template
      shell: powershell
      run: |
        $config = Get-Content "configuration.json" | ConvertFrom-Json

        # Inject Source Config
        $config.MigrationTools.Endpoints.Source.Collection = "https://dev.azure.com/${{ github.event.inputs.source_org }}/"
        $config.MigrationTools.Endpoints.Source.Project = "${{ github.event.inputs.source_project }}"
        $config.MigrationTools.Endpoints.Source.Authentication.AccessToken = "${{ secrets.SOURCE_PAT }}"

        # Inject Target Config
        $config.MigrationTools.Endpoints.Target.Collection = "https://dev.azure.com/balraj-test-org/"
        $config.MigrationTools.Endpoints.Target.Project = "${{ github.event.inputs.destination_project }}"
        $config.MigrationTools.Endpoints.Target.Authentication.AccessToken = "${{ secrets.DESTINATION_PAT }}"

        # Save config
        $config | ConvertTo-Json -Depth 100 | Out-File "config.json" -Encoding utf8

    - name: Run DevOps Migration
      shell: powershell
      run: |
        devopsmigration execute -c config.json
